name: 'First interaction'
description: 'Greet new contributors when they create their first issue or open their first pull request'
author: 'GitHub'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  issue-message:
    description: 'Comment to post on an individual''s first issue'
  pr-message:
    description: 'Comment to post on an individual''s first pull request'
outputs:
  FIRST:
    description: 'Boolean that tells if the user has merged first pull request.'
  USER:
    description: 'Returns the username of the issue/PR author'
runs:
  using: 'docker'
  image: 'Dockerfile'
